### PR TITLE
Export module with browserify and fix some errors

### LINKED ISSUE #18: Running demo
Hi guys,
I can't get your map to run. I tried importing it into our app and initialize it which won't work (no errors but nothing is displayed either).
Checking out your develop branch directly and opening the `index.html` also only gives me a blank page and throws two errors:

`Uncaught ReferenceError: require is not defined`
`Uncaught ReferenceError: PokeMap is not defined`

The live demo from your github pages works but is 20 days old.

I would really a need a working version of your map as soon as possible!

### PR DESCRIPTION
**Pull request by johartl**
- Added browserify to bundle your sources and transpile them to ES5.
- Removed constructor parameters which don't adhere to the PokeMap interface (`coordinates`, `zoomLevel`, `timeRange`)
- Commented out method call to `initStyles` which cause errors (Please try to fix them yourself)
- Fixes #18

### CODE REVIEW

**Comment by oleks-fedotov** [comment]
Thanks for pull request. Unfortunately, i will not merge it. Because you removed an options part from the PokeMap component, they are optional and i think they can stay.

As you did I changed the package.json file, so that leaflet will be included. 

Also it's strange, but styles are working in our case. 
Can you please clarify, which error did you get from initStyles?

**Comment by johartl** [comment]
I removed the options which are not in the specification here https://github.com/PokemonGoers/Catch-em-all/issues/24. I think if you need to set a location after you've initialized the map you can just call `pokeMap.goTo(cordinates, zoomLevel)` right after the initialization. No need to put this in the constructor in my opinion.

The problem with the styling is that you're creating a string containing all your CSS and then you replace `#mapid` by `htmlElement`. The result of this is

```
<style>#[object HTMLDivElement] .pokemon-details-popup {text-align: center;width: 300px; }#[object HTMLDivElement] .pokemon-details-popup .pokemon-image {vertical-align: top;float: left;}#[object HTMLDivElement] .pokemon-details-popup .pokemon-name {display: inline-block;margin-right: 15px;}#[object HTMLDivElement] .pokemon-details-popup .details-block {text-align: left;margin-top: 5px;}#[object HTMLDivElement] .pokemon-details-popup .details-attribute-name {font-weight: bold;padding-left: 5px;padding-right: 10px;font-size: 1.2em;}#[object HTMLDivElement] .pokemon-details-popup .details-attribute-value {float: right;padding-top: 0.2em;}</style>
```

Obviously `#[object HTMLDivElement]` is not a valid CSS selector. After appending this to the body (which is really bad practice btw) our entire app crashes. You should really package the CSS into your bundle. Please have a look at https://www.npmjs.com/package/browserify-css, this might be what you're looking for.

**Comment by oleks-fedotov** [comment]
@johartl thanks for the link, already changed the styles part.

You're absolutely right about the `pokeMap.goTo(cordinates, zoomLevel)`, we just left them there for convenience of future usage, since they are optional.

**Comment by johartl** [comment]
Okay that's a lot better already. 
However, with the current setup we will have two files: `pokemap.bundle.js` and `style.bundle.js`. When I import your package all I will get is the `pokemap.bundle.js` because this is the only file referenced in your package.json for the `main` key. 
Fortunately we can work around this very easily. All you have to do is..
1. In your `main.js` add the following at the top
   `require('../style.css');`
2. In your `package.json` change
   `"postinstall": "browserify module/main.js -o pokemap.bundle.js -t es6ify -t browserify-css --standalone PokeMap"`
3. In your `index.html` remove the `<script src="style.bundle.js"></script>` tag
4. In your `package.json` move `browserify-css` from `devDependencies` to `dependencies`

**Comment by johartl** [comment]
I will close this now.

**Pull request closed without merging**
